"""initial schema

Revision ID: ef78ccfb0247
Revises: 
Create Date: 2026-09-07 03:34:07.583703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef78ccfb0247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointment',
    sa.Column('appt_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='appointmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('appt_id')
    )
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_table('healthrecord',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sexoption'), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('blood_glucose_mgdl', sa.Float(), nullable=True),
    sa.Column('hba1c_level', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('chest_pain_type', sa.Enum('typical_angina', 'atypical_angina', 'non_anginal', 'asymptomatic', name='chestpaintype'), nullable=True),
    sa.Column('exercise_angina', sa.Boolean(), nullable=True),
    sa.Column('resting_ecg', sa.Enum('normal', 'st_t_abnormality', 'left_ventricular_hypertrophy', name='restingecg'), nullable=True),
    sa.Column('st_slope', sa.Enum('upsloping', 'flat', 'downsloping', name='stslope'), nullable=True),
    sa.Column('st_depression', sa.Float(), nullable=True),
    sa.Column('major_vessels_colored', sa.Integer(), nullable=True),
    sa.Column('thalassemia', sa.Enum('unknown', 'normal', 'fixed_defect', 'reversible_defect', name='thalassemia'), nullable=True),
    sa.Column('smoking_history', sa.Enum('never', 'no_info', 'current', 'former', 'ever', 'not_current', name='smokinghistory'), nullable=True),
    sa.Column('drinks_alcohol', sa.Boolean(), nullable=True),
    sa.Column('physically_active', sa.Boolean(), nullable=True),
    sa.Column('has_hypertension', sa.Boolean(), nullable=True),
    sa.Column('has_heart_disease', sa.Boolean(), nullable=True),
    sa.Column('date_recorded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_healthrecord_patient_id'), 'healthrecord', ['patient_id'], unique=False)
    op.create_table('consultation',
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('appt_id', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prescribed_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appt_id'], ['appointment.appt_id'], ),
    sa.PrimaryKeyConstraint('consult_id'),
    sa.UniqueConstraint('appt_id')
    )
    op.create_table('prediction',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('heart_disease', 'diabetes', 'hypertension', name='condition'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_class', sa.Enum('low', 'elevated', name='riskclass'), nullable=False),
    sa.Column('date_generated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['healthrecord.record_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_prediction_record_id'), 'prediction', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_record_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_table('consultation')
    op.drop_index(op.f('ix_healthrecord_patient_id'), table_name='healthrecord')
    op.drop_table('healthrecord')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
